### ISSUE TITLE
Label feature suggestion

### ISSUE THREAD

**Issue by umutucler** [alizahid/slinky#11]
Thanks for this awesome little plugin!

I have a wish for an extra little detail for UX. It would be a cool feature and informative if it could show the last label and the current label title.

![img_0364](https://cloud.githubusercontent.com/assets/5963503/12859915/82158cba-cc59-11e5-8459-5bccb12059d0.JPG)

**Comment by Snowbell92** [comment]
sorry to revive this, but I have a request too, regarding labels. Is it possible to add a title for the first level, ie, before user navigates to any submenu? kind of like jquery mmenu's header.
