### ISSUE TITLE
Excluding Top Level with no children

### ISSUE THREAD

**Issue by br-designer** [alizahid/slinky#2]
Hi, I was wondering how to exclude top level items, that do not have children, from having their links stripped? As an example, home and contact wouldn't have children normally.

**Comment by alizahid** [comment]
@br-designer I've finally updated the plugin. Please check if your issue has been resolved now. Also, help me test the plugin for any bugs, if you're still using it.

**Comment by alizahid** [comment]
@pixelagent Please see #4 for your request.
