### ISSUE TITLE
modal compatibility

### ISSUE THREAD

**Issue by VisualTrauma** [alizahid/slinky#23]
The plugin doesn't seem to work on modal.

**Comment by alizahid** [comment]
@VisualTrauma Could you show an example of what you mean?

**Comment by VisualTrauma** [comment]
Sorry for the late reply. I tried this project to be placed inside a modal but it fails to correctly render the plugin. Have you tried to use it in modal? If it renders correctly please ignore and close this issue, maybe there is something wrong with my implementation. Thank you for replying. :)

**Comment by alizahid** [comment]
Could you make a Fiddle or something?
