### ISSUE TITLE
api usage

### ISSUE THREAD

**Issue by mediaaffect** [alizahid/slinky#24]
Trying to use the api and a bit confused how it works.

		$('.buttonclass').click(function(){
		    $('#menu').slinky().jump('ul.firstLevel'); 
or
		    $('#menu').slinky().home();
		});

When using home the back buttons start repeating.

**Comment by alizahid** [comment]
Each time you call `$('#menu').slinky()`, you duplicate the menu!

What you need is call `$('#menu').slinky()` once, and store the response like 

    const menu = $('#menu').slinky()

And then use it whenever you want like

    $('.buttonclass').click(() => menu.jump('ul.firstLevel'))
