### ISSUE TITLE
Destroying a menu

### ISSUE THREAD

**Issue by saltcod** [alizahid/slinky#26]
Hey!

Wondering how to destroy a menu. I'm assuming destroy === reset?  I want to reset the menu to original state when I close the hamburger menu. 

menu.slinky().destroy() => destroys the menu all together, so when I reopen the hamburger menu, it's completely unstyled.

menu.slinky().home() => makes the menu disappear when I reopen the hamburger menu.

Is there another way to reset the menu when I close the hamburger? 

Appreciate the time!

**Comment by alizahid** [comment]
Hey! Take a look at [this issue](https://github.com/alizahid/slinky/issues/24#issuecomment-315682694).

**Comment by saltcod** [comment]
aah gotcha. Sweet! thank you!
