### ISSUE TITLE
jquery sliding menu inside another plugin won't load

### ISSUE THREAD

**Issue by dirtandrust** [alizahid/slinky#3]
Is there some sort of callback i can use in my own custom jquery to load your plugin? For some reason if your sliding menu code isn't visible (hidden by a div on top) it doesn't load. Any help appreciated! :) 
(your code starts at "Artist" as I'm using your demo html in my code running your plugin):
![screen shot 2015-01-23 at 4 01 36 pm](https://cloud.githubusercontent.com/assets/1700664/5869155/2fe75370-a319-11e4-9592-a6bd9865cff1.png)

**Comment by alizahid** [comment]
@dirtandrust Hi. Can you show me the code?

**Comment by dirtandrust** [comment]
Hi sure! I've posted the code here: http://dirtandrust.com/wp-content/uploads/super_menu/step4.html

Steps to reproduce: 

1. Go to 320 viewport width
2. Click menu icon
3. First tab has your plugin
4. Click first item, then open the browser viewport to maybe 600px (don't go past 767px or you'll break the test)
5. I see your code is working but it's just not showing where i want it

Maybe the issue is conflicting css? Not sure. Any help appreciated.

Nathaniel

**Comment by dirtandrust** [comment]
I think the only issue that needs to be solved in my case is for your plugin to be responsive - currently it only fires once to detect size but should fire on any window change.

**Comment by alizahid** [comment]
Ah, I feel you. Will get on it soon.

**Comment by alizahid** [comment]
@dirtandrust I've finally updated the plugin. Please check if your issue has been resolved now. Also, help me test the plugin for any bugs, if you're still using it.
