### ISSUE TITLE
slinky menu doesn't work on some phone browsers

### ISSUE THREAD

**Issue by boulmerhras** [alizahid/slinky#31]
hello,
i have added slinky menu to my website, it works perfectly in all browsers except some phone browsers, like samsung browser, or iphone default browser, 
Any suggestion?

**Comment by ScoutsOut** [comment]
@boulmerhras - I'm not a maintainer but it would be helpful to the community to provide greater details regarding the issues you ran into.

What exactly were the issues? Were they performance-based issues? Presentation (CSS) layer issues?
JS issues?

Thanks again. Provide some details and I'm sure someone will comment. @alizahid

**Comment by alizahid** [comment]
Yeah, really need more details on this. Steps to reproduce, etc.

Since this issue is very old, I'm closing it. You can create a new one if you're still seeing this.
