### ISSUE TITLE
.home() and .jump() not working properly

### ISSUE THREAD

**Issue by iakwvina** [alizahid/slinky#32]
I am calling $("#menu").slinky().home() and the root menu is appering left: -300%.
The .jump() function on the other hand creates multiple back buttons on the top of the sub menu.

Any suggestion to fix them?

**Comment by alizahid** [comment]
Every time you call `.slinky()`, it recreates the menu.

You need to store the reference to Slinky like

```
const menu = $('#menu').slinky()
```

And then when you need to go home

```
menu.home()
```

Or jump like

```
menu.jump('.somewhere')
```
