### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by NielsOetang** [alizahid/slinky#35]
My menu won't load in a Firefox browser, normal?

**Comment by alizahid** [comment]
@NielsOetang Shouldn't be normal. Which version are you trying with?

**Comment by NielsOetang** [comment]
[slinky.pdf](https://github.com/alizahid/slinky/files/2430398/slinky.pdf)
Is use the slinky.js file showed in .pdf in this way:
        
        <script src="js/slinky.js"></script>
        <script>
            const slinky = $('#kov-slide-menu').slinky()
        </script>

**Comment by alizahid** [comment]
Sorry, I meant which version of Firefox are you using?

**Comment by NielsOetang** [comment]
Version 60.0.1 (64-bit)

**Comment by alizahid** [comment]
Hey @NielsOetang. I wasn't able to reproduce this. I tried on Firefox 62 and 68.

Were you able to fix it?
