### ISSUE TITLE
Set sub menu as active on init

### ISSUE THREAD

**Issue by jmarsh376** [alizahid/slinky#4]
Hi Ali
I don't know if this is more of a request rather than an issue.
But is it possible to set a menu item as active?

meaning if it is for e.g 3 layers down when the page loads it is already on that item and it does not reset to the top level like it currently does?

Cheers,

Jack

**Comment by alizahid** [comment]
Hi. I like your idea. Will get on it soon.

**Comment by jmarsh376** [comment]
Great thank you!
