### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by umutucler** [alizahid/slinky#7]
Hi Ali,

This is almost exactly what I was looking for but I'm curious about which browser are supported and smartphone browsers?

I've tested it on Android v2.3.5 native browser and the ul's are not hidden.

Best regards
Umut Ücler

**Comment by alizahid** [comment]
Hey @umutucler,

I don't have an older Android device to test it on. Can you show me a screenshot of what you see?

**Comment by umutucler** [comment]
Hi,

Here is a screenshot




Med venlig hilsen / Best regards

Umut Ücler

**Comment by umutucler** [comment]
The image was somehow not added. Here it is.
![img_4152](https://cloud.githubusercontent.com/assets/5963503/7855164/acd5845c-051f-11e5-909d-3b6cb0e26b95.JPG)

**Comment by alizahid** [comment]
@umutucler I've finally updated the plugin. Please check if your issue has been resolved now. Also, help me test the plugin for any bugs, if you're still using it.

**Comment by umutucler** [comment]
Hi Ali,
Thanks! I have been ill for a long time and haven't been able to work on the project. Starting again now and will report back with bug findings and suggestions.
