### ISSUE TITLE
Responsive issue on resize of window

### ISSUE THREAD

**Issue by umutucler** [alizahid/slinky#8]
Hi Ali,

I found an issue that I thought you might wanted to know. Trying to solve it myself.
1. If you shrink down the width of the window after it has loaded, the "greater than" charachter disappears.
2. If you load with you browser width low, and the drag your window to maximum, the hidden ul's is being exposed.
![capture](https://cloud.githubusercontent.com/assets/5963503/7858228/f240adfc-0536-11e5-9679-fc677308c317.PNG)

**Comment by alizahid** [comment]
@umutucler This is what happens when you use too much JS, and not enough CSS. :grinning:

A rewrite of this plugin is required to fix the bugs and add the requested features. I'll get on it real soon!

**Comment by umutucler** [comment]
Oh, had similar problems on a project I did earlier this year :D



—
Med venlig hilsen / Best regards
Umut Ücler

**Comment by NeXTs** [comment]
Any updates on this?

**Comment by alizahid** [comment]
@umutucler @NeXTs Yes, there's a new version out now. Please have a look, it should fix your troubles. Also, help me test the plugin for any bugs, if you're still using it.

**Comment by umutucler** [comment]
Hi Ali, I've updated your plugin. The bugs from before has been solved and I love that you added the possibility to use a links own label in stead og "back". But I found a problem. 
When I set label to true, it repeats the the first ul several times with a backlink "less than" sign on the left and breaks the function. I'm using it in Wordpress and you can see an example here http://tast1.dk/yousee/

**Comment by alizahid** [comment]
@umutucler It should be fixed now.

**Comment by umutucler** [comment]
Thanks! Everything seems to work great. 
I have a wish for an extra little detail for UX. It would be a cool feature and informative if it could show the last label and the current label title.
![img_0364](https://cloud.githubusercontent.com/assets/5963503/12809778/14aeb206-cb22-11e5-9a5d-43b05ff05181.JPG)

**Comment by alizahid** [comment]
@umutucler Create a new issue and label it `Enhancement`.

**Comment by umutucler** [comment]
Done but I can't actually add a label
